site_name: |
  Aarhus/Barcelona Analysis & Modelling Group <br>
  Lab Wiki

nav:
  - Home: index.md
  #- About: about.md
  - Resources:
    - Datasets: datasets.md 
    - FAQs:
      - Accessing Servers: server_faq.md
  - Dates & Deadlines: dates.md
  - Code: code.md
  - Papers: papers.md

plugins:
  - search
  - bibtex:
      bib_file: "ref.bib"
      citation_style: apa


theme:
  name: material
  palette:
    primary: custom
    accent: custom
  font:
    text: DM Sans       # body text
    code: JetBrains Mono  # code blocks


extra_css:
  - extra.css

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde